### PR TITLE
20291 move app to app directory

### PR DESCRIPTION
**Pull request by EPortman**
*Issue #:* /bcgov/entity###

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by ozamani9gh — APPROVED** [review]
i am ok with all this new code

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-769-a548hq0u.web.app

**Comment by EPortman** [comment]
Do not Merge yet

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-769-upuk1kjk.web.app

**Pull request merged**
