### PR TITLE
17045 - Fix content width issue

### PR DESCRIPTION
**Pull request by leodube-aot**
*Issue #:* /bcgov/entity#17045

*Description of changes:*
- Fix bug introduced in #641 causing the screen content to not take full screen width (see screenshot)

image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
LGTM

Probably should update app version.

Merge when ready.

**Review by JazzarKarim — APPROVED** [review]
~I wonder where the GCB went 😕 Might be worth asking Patrick.~ Never mind.

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-644-2rb6gz53.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-644-2rb6gz53.web.app

**Review by ketaki-deodhar — APPROVED** [review]
checked temp url and Looks good!

**Pull request merged**
