### PR TITLE
initial cleanup: moved files from client/ to root

### PR DESCRIPTION
**Pull request by severinbeauvais**
*Issue #:* /bcgov/entity#6581

*Description of changes:*
- moved files from client/ to root
- updated jest.config.js
- updated tsconfig.json (re: esnext)
- updated app version to 2.0.0
- updated git ignore file
- updated working-directory in ci.yml and cd.yml

NOTE: more big changes to come in another PR

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by severinbeauvais** [comment]
^^ I think the CI job failed because it's expecting to run make inside client/ (which I flattened).

@pwei1018 Is it easy to have a CI job for this branch (release-2.0) be different than the master branch?

**Comment by thorwolpert** [comment]
re: Makefile
it runs **npm ci** which requires a **package-lock.json ** but it looks like it was deleted.

**Comment by severinbeauvais** [comment]
Fixed! But `cd.yml file` still refers to master branch. We'll need to update this when we have an environment to deploy to.

**Review by kialj876 — APPROVED** [review]

**Comment by severinbeauvais** [comment]
> @pwei1018 Is it easy to have a CI job for this branch (release-2.0) be different than the master branch?

We'd like this branch (release-2.0) to deploy to a new environment. What's needed for this? Do we need a new ticket?

**Comment by pwei1018** [comment]
> > @pwei1018 Is it easy to have a CI job for this branch (release-2.0) be different than the master branch?
> 
> We'd like this branch (release-2.0) to deploy to a new environment. What's needed for this? Do we need a new ticket?

We are waiting for the WAM change for the domain name in Openshift4. I hope we can get it done in dev this week.

**Pull request merged**
