### PR TITLE
16642 Implement Amalgamation NR

### PR DESCRIPTION
**Pull request by kzdev420**
*Issue #:* /bcgov/entity#16642

*Description of changes:*

- Add the business type more
- Update Name flow

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-653-9ud6r9r0.web.app

**Review by severinbeauvais — APPROVED** [review]
Looks good to me. Great job, Kevin!

**Review by JazzarKarim — APPROVED** [review]
LGTM and don't forget package version please Kevin! 👍

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-653-9ud6r9r0.web.app

**Comment by JazzarKarim** [comment]
Kevin, I see you have moved this ticket to UX Assurance/Verification. Don't forget to merge when ready please!

**Pull request merged**
