### PR TITLE
#8901 name choice should not have designation added

### PR DESCRIPTION
**Pull request by eve-git**
Name choice should not have designation added

*Issue #:* /bcgov/entity#8901

*Description of changes:*
1. If a designation has NOT been setup before editing the name, the designation is NOT in the name when no designation input available.
2. If the designation has been setup before editing the name, the designation goes with the name when no designation input available.
3. Removed a piece of the code which never reachable.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by severinbeauvais** [comment]
What are your test cases for this change? Please list them in the ticket.

**Review by severinbeauvais — COMMENTED** [review]
Looks OK but I'd like to verify the test cases pass before approving this change,

**Comment by eve-git** [comment]
I just removed designation that added after the first create. In the test case below, the value of name variable is 'TEST ABC INC.'. Please check if the results are expected.
test 1.
1. Create a NR of BC Limited company with 'INC' designation
2. Edit after payment

**Comment by severinbeauvais** [comment]
This is not what I asked for. QA does not look at PRs for test notes, so they will not know what you have tested and what they should verify. Please add your test cases to the ticket.

I saw your code change, and I think there may be multiple paths that go through there. You need to test as many of those paths as possible to verify that all cases work as expected. Off the top of my head I can think of the following scenarios:
- first create
- other create? or next + back? what about Start Over and Exit?
- edit flow (after paying for it and before it's approved)
- one choice requested
- mutiple choices requested
- BC jurisdiction
- other jurisdictions

Add anything else you can think of to this list.

**Comment by eve-git** [comment]
I did do several test cases for unit test. I had questions for the results, so that I attached the screenshot in this ticket. I wonder if it is what expected?

The code changes are nothing special and only related to the display of the names. The steps of reproduce the error are in the ticket. In the case, should the tester create test cases?

**Comment by severinbeauvais** [comment]
> I did do several test cases for unit test. I had questions for the results, so that I attached the screenshot in this ticket. I wonder if it is what expected?
> 
> The code changes are nothing special and only related to the display of the names. The steps of reproduce the error are in the ticket. In the case, should the tester create test cases?

THIS is not the ticket. THIS is the Pull Request.

Yes, the tester is free to create their own test cases. I am looking for evidence that you have run a variety of test cases to verify the fix and that nothing else is impacted.

**Comment by eve-git** [comment]
OK, I will attach my question to the ticket. Thanks.

**Review by severinbeauvais — APPROVED** [review]
I approve. Thanks for the tests!

**Review by severinbeauvais — COMMENTED** [review]
The rebase apparently cleared out your version update - please update version again.

**Review by severinbeauvais — APPROVED** [review]

**Comment by eve-git** [comment]
@cameron-freshworks Can you please review the changes? Thanks!

**Review by cameron-freshworks — APPROVED** [review]
You bet, looks good!

**Pull request merged**
