### PR TITLE
24332 - Display Change Name Now Button for Name Change NR

### PR DESCRIPTION
**Pull request by meawong**
*Issue #:* /bcgov/entity#24332

*Description of changes:*
- Add missing logic to display **Change Name Now** button

image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-783-nd3ps7sv.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-783-nd3ps7sv.web.app

**Review by rarmitag — APPROVED** [review]

**Pull request merged**
