### PR TITLE
18058 - Names Request UI - Fixed wording on landing page

### PR DESCRIPTION
**Pull request by Rajandeep98**
*Issue #:* 18058 -  Names Request UI - Fixed wording on landing page

*Description of changes:*
updated wording for landing page

### CODE REVIEW

**Review by eve-git — APPROVED** [review]
LGTM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-727-shla47td.web.app

**Review by ozamani9gh — COMMENTED** [review]
looks good

**Pull request merged**
