### PR TITLE
Remove EP and jurisdiction

### PR DESCRIPTION
**Pull request by kzdev420**
*Issue #:* /bcgov/entity#16642

*Description of changes:*

- Remove the EP jurisdiction
- Remove business lookup

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-654-xqeoznop.web.app

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Review by JazzarKarim — APPROVED** [review]
LGTM

**Comment by severinbeauvais** [comment]
Kevin, please merge when ready. (I will need to rebase to this ASAP.)

**Comment by kzdev420** [comment]
> Kevin, please merge when ready. (I will need to rebase to this ASAP.)

I just committed for remove Business-Lookup. If it looks good to me, I will merge

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-654-xqeoznop.web.app

**Comment by kzdev420** [comment]
> > Kevin, please merge when ready. (I will need to rebase to this ASAP.)
> 
> I just committed for remove Business-Lookup. If it looks good to me, I will merge

I merged it

**Pull request merged**
