### PR TITLE
Update Devops directory location

### PR DESCRIPTION
**Pull request by EPortman**
*Issue #:* /bcgov/entity###

*Description of changes:*
- Had to move the devops directory to the app/ folder for the CD to work. This is because the CD needs the vaults.env values under this directory. 
- Also updated the cloudbuild to run the smoke test on the /gcbrun trigger. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-770-aem5dett.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-770-aem5dett.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-770-aem5dett.web.app

**Review by rarmitag — APPROVED** [review]

**Pull request merged**
