### PR TITLE
Rebasing feature branch with main

### PR DESCRIPTION
**Pull request by JazzarKarim**
*Issue #:* /bcgov/entity#16641

*Description of changes:*
- Rebasing the branch with main. This is to pull the latest changes of main into the feature branch.

This was a very weird rebase and it took more time than I had hoped it would.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-659-lvih9we3.web.app

**Review by severinbeauvais — APPROVED** [review]
LGTM. I compared these PR changes with https://github.com/bcgov/namerequest/compare/feature-way-of-navigating...main and they match (except for the change in conversion-types.ts which is already in the feature branch).

**Review by ketaki-deodhar — APPROVED** [review]
cross checked commits with main (there were only 3). Looks good

**Review by chenhongjing — APPROVED** [review]
LGTM 🐱

**Pull request merged**
