### PR TITLE
Hide Action button when changing name and Go To Colin Button visible

### PR DESCRIPTION
**Pull request by eve-git**
*Issue #:* /bcgov/entity###
https://github.com/bcgov/entity/issues/20529

*Description of changes:*
Hide action button when changing name to a numbered name and the legal type is not supported by FF 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-757-p8kfadau.web.app

**Review by severinbeauvais — APPROVED** [review]
Looks good, Eve!

**Comment by severinbeauvais** [comment]
@eve-git , did you change the FF to test this scenario (as described in the ticket)?

**Review by ketaki-deodhar — APPROVED** [review]
Looks good!

**Comment by eve-git** [comment]
> @eve-git , did you change the FF to test this scenario (as described in the ticket)?

Yes, I changed FF and tested, it works on both of the two options. I think the coding logic is good too.

**Pull request merged**
