### PR TITLE
6566 - Save homeJurisNum for international jurisdiction

### PR DESCRIPTION
**Pull request by andrepestana-aot**
*Issue #:* /bcgov/entity#6566

*Description of changes:*

- Fixed saving homeJurisNum for international jurisdiction; 
- Added validation for the home jurisdiction number <= 40;
- Removed option for the user not enter a home jurisdiction number for international jurisdiction.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
Looks OK to me. Does it test correctly? What about in the NR edit flow?

**Comment by andrepestana-aot** [comment]
> Looks OK to me. Does it test correctly? What about in the NR edit flow?

Yes, it tests correctly. The NR edit flow doesn't change homeJurisNum. Thanks for remind me.

I'm gonna wait for @cameron-freshworks to review it before merging.

**Review by cameron-freshworks — APPROVED** [review]
The code looks good! 
My concern is the same as Severins, Name Request can be fragile in ways.
I'd definitely do some thorough testing of BC Mras and Extra Pro Mras searches before merging, just to make sure 👍

**Comment by andrepestana-aot** [comment]
> The code looks good!
> My concern is the same as Severins, Name Request can be fragile in ways.
> I'd definitely do some thorough testing of BC Mras and Extra Pro Mras searches before merging, just to make sure 👍

ok! Thanks. I'll do more tests. I also think it should be able to update the home juris number on edit mode. I'll confirm that.

**Comment by andrepestana-aot** [comment]
The home jurisdiction number won't be changed in the edit flow and now we need to ensure that the user enters a home jurisdiction number for international jurisdictions.

**Review by severinbeauvais — APPROVED** [review]

**Review by cameron-freshworks — APPROVED** [review]

**Pull request merged**
