### PR TITLE
Default the "I am completing this reservation on my own behalf" to be unselected

### PR DESCRIPTION
**Pull request by eve-git**
*Issue #:* /bcgov/entity#8111

*Description of changes:*
1. set the default value of actingOnOwnBehalf to false;
2. add (Optional) text on the First and Last name in Client section in applicant-info-2.vue

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by cameron-freshworks — COMMENTED** [review]
Code looks good!

Was the outcome of the solution conversation to leave the checkbox in but change the default value?

**Comment by andrepestana-aot** [comment]
I think you missed the package.json file.

**Review by andrepestana-aot — CHANGES_REQUESTED** [review]
Please commit the package.json

**Review by severinbeauvais — COMMENTED** [review]
I have reviewed and will approve this once the other comments are resolved.

**Review by severinbeauvais — APPROVED** [review]

**Review by andrepestana-aot — APPROVED** [review]
LGTM

**Pull request merged**
