### PR TITLE
Updated CD.yml file to the newer version.

### PR DESCRIPTION
**Pull request by EPortman**
*Issue #:* /bcgov/entity###

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by rarmitag — APPROVED** [review]

**Review by rarmitag — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-772-n5b4j6ea.web.app

**Pull request merged**
