### PR TITLE
Fixed in response to Yui's comment

### PR DESCRIPTION
**Pull request by JazzarKarim**
*Issue #:* /bcgov/entity#16635

*Description of changes:*
- This fixes the comment Yui mentioned regarding the registration/incorporation flow. Yui's comment: https://github.com/bcgov/entity/issues/16635#issuecomment-1642807197
- The behavior is exactly like in PROD now (which is what we want according to Yui).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-628-mefl84wf.web.app

**Review by severinbeauvais — APPROVED** [review]
Is that how it's done elsewhere?

See line 62. Thoughts?

**Comment by JazzarKarim** [comment]
> Is that how it's done elsewhere?
> 
> See line 62. Thoughts?

This is not how it's done currently in main branch. I tried to match between the two but there's too much code to dig in (plus a lot of stuff is now different due to the changes you and I have made). So, I had to improvise and come up with my own solution 😎

Also, regarding line 62, that's how I originally was trying to do it. It wasn't working though (when society is selected, entity_type_cd was not being changed).

**Comment by severinbeauvais** [comment]
Oh well, it's fine then.

**Review by leodube-aot — APPROVED** [review]
LGTM Karim!

**Pull request merged**
