### PR TITLE
Updated version

### PR DESCRIPTION
**Pull request by jamespaologarcia**
*Issue #:* /bcgov/entity#17914

Updated version

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by JazzarKarim — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-744-91zl7o4u.web.app

**Review by severinbeauvais — APPROVED** [review]
This was not necessary but.. ok.

**Comment by severinbeauvais** [comment]
> This was not necessary but.. ok.

OK, I just saw Eve's request in Teams now. So this was a legitimate change. Sorry, I was wrong!

**Pull request merged**
