### PR TITLE
17153-Add CP entity type case

### PR DESCRIPTION
**Pull request by ketaki-deodhar**
*Issue #:* /bcgov/entity#17153

*Description of changes:*

Issue; Riyaz could not incorporate a CP from a NR. Received error when Incorporate Now clicked

Solution: Add CP entity type case

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by JazzarKarim** [comment]
Don't forget to assign yourself and update package version please Ketaki 🙌

**Comment by ketaki-deodhar** [comment]
> Don't forget to assign yourself and update package version please Ketaki 🙌

Won't but thanks for the reminder. I usually update it after reviews are done and ready to go :)

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-636-tyxph75s.web.app

**Review by JazzarKarim — APPROVED** [review]

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Comment by ChrisGabel23** [comment]
Would it be beneficial to pre-emptively add any other entity types not already on the list?

**Pull request merged**
