### PR TITLE
17672 changed misleading error messages to include 'eligible'

### PR DESCRIPTION
**Pull request by PaulGarewal**
*Issue #:* /bcgov/entity#17672

*Description of changes:*

- changed the business lookup status error message in change business name and in reactivate business name to:
                      "**No eligible historical business found**" and "**No eligible active business found**" 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
Looks good. I'm giving you a ~conditional~ _preliminary_ approval -- please update the app version and commit both package files.

Also, probably not needed for this fix, but you _could_ kick off a GCB build so we can get a temporary URL to verify this PR. Up to you.

**Review by leodube-aot — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-709-98fjqmdo.web.app

**Review by JazzarKarim — APPROVED** [review]
Great job Paul! Your first FE ticket 🥳

**Pull request merged**
