### PR TITLE
Updated package.json to create a dummy PR

### PR DESCRIPTION
**Pull request by severinbeauvais**
Do not commit this change. It is only to create a dummy PR so that we can build a previous tempory version of this code to facilitate testing.

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-702-778wp0h0.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-702-wglnu29x.web.app

**Comment by severinbeauvais** [comment]
This PR is no longer needed. I'm closing it.

**Pull request closed without merging**
