### PR TITLE
Changed character limit for business's legal name

### PR DESCRIPTION
**Pull request by Madhavkapoor28**
*Issue #:* /bcgov/entity#14923

*Description of changes:*

Changed the max character limit for a business's legal name in home jurisdiction.

### CODE REVIEW

**Review by ozamani9gh — COMMENTED** [review]
Please update the package.lock file with a new version number.

feel free to update minor or patch release number.

currently it is "version": "4.1.4",

**Review by seeker25 — APPROVED** [review]

**Comment by seeker25** [comment]
Please update `package.json`, `npm i` should update `package-lock.json` automatically. If you notice too many lines changed in `package-lock.json` might want to check the nodeJs version.

**Review by severinbeauvais — COMMENTED** [review]
The correct way to update the app version is:
- update version in package.json
- run `npm i`
- commit both package.json and package-lock.json

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-601-by5r1j28.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-601-by5r1j28.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-601-by5r1j28.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-601-by5r1j28.web.app

**Comment by severinbeauvais** [comment]
@seeker25 What's the status of this PR? Should someone else take it over and get it reviewed + merged?

**Comment by seeker25** [comment]
Haha not too sure, @pwei1018 over to you

**Comment by pwei1018** [comment]
@severinbeauvais Can you put this change in your pull request and close this one? This one seems hard to solve the conflicts of package-lock.json.

**Comment by severinbeauvais** [comment]
> @severinbeauvais Can you put this change in your pull request and close this one? This one seems hard to solve the conflicts of package-lock.json.

Yes, OK. I will close this PR and create a new one (under my GH id).

**Pull request closed without merging**
