### PR TITLE
Common Component Version Update

### PR DESCRIPTION
**Pull request by cameron-freshworks**
*Issue #:* /bcgov/entity#10922

*Description of changes:*
* Update common components version

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
Basic testing is OK with all these updates?

**Comment by severinbeauvais** [comment]
Need to fix build error before merging.

**Comment by cameron-freshworks** [comment]
> Basic testing is OK with all these updates?

I'll need to run this one, to look into the build error
But yea, unit tests ran without issue!

**Comment by cameron-freshworks** [comment]
> Need to fix build error before merging.

Took me a min to find, but the external package requires our apps webpack config to include `sass-loader` if it's specifying rules on the modules.

**Pull request merged**
