### PR TITLE
20953 update sbc-common-components version

### PR DESCRIPTION
**Pull request by eve-git**
*Issue #:* /bcgov/entity#20953

*Description of changes:*
Update sbc-common-components version

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
Looks good. Do you have a screenshot that shows the updated footer?

**Comment by eve-git** [comment]
> Looks good. Do you have a screenshot that shows the updated footer?

image

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-760-rds46crf.web.app

**Pull request merged**
