### PR TITLE
15183 Added content security policy to genesys web chat

### PR DESCRIPTION
**Pull request by JazzarKarim**
*Issue #:* /bcgov/entity#15183

*Description of changes:*
- Added the Content Security Policy to unblock the execution of the Maximus Web Chat Script in Dev.
genesys in dev

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Comment by severinbeauvais** [comment]
> I don't think the package and package.lock make sense to update here.

If not then how would we know whether Dev or Test or Prod have the needed configuration, other than testing if the new webchat works?

**Comment by seeker25** [comment]
By watching the hash on the image, they should always be checked before deploying. 

Package.json is for the web app, you're making a nginx configuration change.. they're two different concerns.

**Comment by severinbeauvais** [comment]
> Package.json is for the web app, you're making a nginx configuration change (infrastructure related).. they're two different concerns.

They are different things but the webserver config and the app that is served are bundled together.

The app version is just easy to see, in any environment, from which we can deduce whether some features/commits are present or not.

**Pull request merged**
