### PR TITLE
add missing article

### PR DESCRIPTION
**Pull request by bolyachevets**
*Issue #:* https://app.zenhub.com/workspaces/ops-60f8556e05d25b0011468870/issues/gh/bcgov-registries/ops-support/1244

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Review by ozamani9gh — APPROVED** [review]

**Comment by ozamani9gh** [comment]
all checks failed?????

**Comment by bolyachevets** [comment]
> all checks failed?????

need to manually run gcp sandbox deployment

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-613-zgt86z5x.web.app

**Pull request merged**
