### PR TITLE
Populate business lookup search API Key

### PR DESCRIPTION
**Pull request by JazzarKarim**
*Issue #:* /bcgov/entity#16918

*Description of changes:*
- Dummy PR to create a new temporary link

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-648-3ldflrwz.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-648-3ldflrwz.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-648-3ldflrwz.web.app

**Comment by JazzarKarim** [comment]
@severinbeauvais @kzdev420 I've asked Patrick to add the key to the GCB. I've also added it to the `cloudbuild-pr.yaml` file.

The key is being populated:
key being populated

However, It's still not working for some reason.
error search key

**Comment by pwei1018** [comment]
Temporary Url for review: https://namerequest-dev--pr-648-3ldflrwz.web.app

**Review by severinbeauvais — APPROVED** [review]
Ah, so this is a 3-fer:
1. add missing CSP domain
2. add missing key assignment from GCP
3. create temp URL

Looks great! Thanks for doing this!

**Comment by JazzarKarim** [comment]
> Ah, so this is a 3-fer:
> 
> 1. add missing CSP domain
> 2. add missing key assignment from GCP
> 3. create temp URL
> 
> Looks great! Thanks for doing this!

Also, thanks to @pwei1018 for his quick assistance in adding the missing key 🙌 

The demo on Tuesday helped a lot 👍

**Pull request merged**
