### PR TITLE
16643 - Change Name flow

### PR DESCRIPTION
**Pull request by ketaki-deodhar**
*Issue #:* /bcgov/entity#16643

*Description of changes:*

- option to change name of existing company
- For BEN/Bc/CCC/ULC, Named and Numbered flow
- For Other Entities (except XPROs), Existing flow
- For XPROs, choose Jurisdiction and follow XPRO flow
- show button "Change Name Now"
- redirect user to business dashboard (not MBR)

Temporary Url for review: https://namerequest-dev--pr-678-v0l4jlfg.web.app/

Just creating another PR as somehow my earlier branch was messed up during a merge :(  You will see same commits here.
For all your comments, please see https://github.com/bcgov/namerequest/pull/672

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-678-v0l4jlfg.web.app

**Review by JazzarKarim — APPROVED** [review]
👍

**Review by severinbeauvais — APPROVED** [review]
It doesn't look like it was an easy rebase but I compare the changes here with the changes in your previous PR and they look good.

**Pull request merged**
