### PR TITLE
17297   UI tweaks

### PR DESCRIPTION
**Pull request by tshyun24**
*Issue #:* /bcgov/entity#17297

*Description of changes:*
UI tweaks have been done

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namerequest-dev--pr-714-8d5fjuaa.web.app

**Review by severinbeauvais — APPROVED** [review]
LGTM

I also checked the spreadsheet that is linked in the ticket, and all items there are checked off, so it looks like this ticket is complete.

**Comment by JazzarKarim** [comment]
> LGTM
> 
> I also checked the spreadsheet that is linked in the ticket, and all items there are checked off, so it looks like this ticket is complete.

Yes Sev. We also asked Ethan and he told us that everything looks good and has been checked off 👍

**Review by JazzarKarim — APPROVED** [review]
LGTM! 👍

**Review by ketaki-deodhar — APPROVED** [review]
LGTM! 👍

**Pull request merged**
